---
name: new_app
description: A new Flutter project.
publish_to: none
version: 1.0.1
environment:
  sdk: ^3.5.3
dependencies:
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_local_notifications: ^18.0.1
  flutter_native_splash: ^2.4.0
  flutter_svg: ^2.0.10+1
  flutter_timezone: ^4.0.0
  font_awesome_flutter: ^10.7.0
  go_router: ^14.3.0
  google_nav_bar: ^5.0.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  meta: ^1.15.0
  permission_handler: ^11.3.1
  shared_preferences: ^2.4.0
  smooth_page_indicator: ^1.2.0+3
  timezone: ^0.10.0
  flutter_localizations:
     sdk: flutter
dev_dependencies:
  build_runner: ^2.1.8
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.1
flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#0C1320"
  image: assets/images/logo.png
  android_gravity: center
  ios_content_mode: scaleAspectFill
  fullscreen: true
  android_12:
    color: "#0C1320"
    image: assets/images/logo.png
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
flutter_intl:
  enabled: true
